### ISSUE TITLE
pkconfig mpi dependency doesn't work on Sunspot

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-bedrock#17]
If I understand https://github.com/mochi-hpc/mochi-bedrock/blob/main/CMakeLists.txt#L82 correctly, it is adding an explicit "mpi" dependency in the .pc file for bedrock.

On Sunspot (possibly other platforms, this just happens to be where I'm testing now) this causes the autoconf tests in mochi-bedrock to fail with the following:

```
configure:17573: checking for BEDROCK
configure:17580: $PKG_CONFIG --exists --print-errors "bedrock-server"
Package mpi was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'mpi', required by 'bedrock-server', not found
configure:17583: $? = 1
```

Sunspot uses mpich, which installs an `mpich.pc` file, not a `mpi.pc` file, so pkgconfig cannot find this dependency.

I'm not sure what the correct solution is.  Maybe just drop the explicit mpi dependency in the .pc file? 

@kaushikvelusamy

**Comment by mdorier** [comment]
Ok I think I added this "mpi" dependency because if you have compiled bedrock with MPI support (which is the default) then whatever you link against bedrock will need to link against MPI as well. For instance bake, which is based on pkg-config for resolving dependencies, will link its bedrock module against bedrock by searching for it using pkg-config. If it doesn't link against MPI as well, you will get link errors, which means the problem gets pushed up to Bake: if you want bedrock support, you have to build bake with an MPI compiler wrapper...

Not sure what's the best solution. CMake keeps better track of those dependencies than autotools/pkg-config, so cmake-based projects (e.g. yokan, warabi, mofka, etc.) don't have this problem.

**Comment by carns** [comment]
mpi actually is not required to be listed here because it is an indirect dependency.

(mochi-ssg's pc file does not have an mpi requirement in the .pc file either for example, and it has worked fine for both cmake and autoconf things that use it, both within and outside of spack.)

Hypothetically, if we supported static builds, then mpi would need to be one of the `private` requirements (because static library .a archives do not have a way to embed their own dependencies so you have to preserve the whole chain.  Luckily we don't support that mode because you would actually need all of the other dependencies on external libraries as well to make that work, like json parsers, serializers, loggers, etc. not just mpi).

That's not really relevant for us because we always dynamically link. The bedrock .so has a dependency on mpi built into it without help from the build system.  You can check with `ldd` on the .so file, and the path to the .so that it depends on is resolved either via rpath or LD_LIBRARY_PATH.  No other information is needed at compile time or runtime.

FWIW on modern systems the .pc files are mostly relevant for expressing the direct requirements (i.e., what cflags and ldflags are needed to use the top level library you are linking against).

**Comment by mdorier** [comment]
Ok, I committed the fix directly to the main branch.
