### ISSUE TITLE
loading ssg config at scale

### ISSUE THREAD

**Issue by roblatham00** [mochi-hpc/mochi-bedrock#7]
I found https://github.com/mochi-hpc/mochi-bedrock/blob/main/src/SSGManager.cpp#L266 where bedrock loads the ssg  group file.  What happens when  thousands of clients load the ssg group file at the same time?

In what was inarguably premature optimization I wrote benvolio's `bv_init` https://github.com/mochi-hpc/benvolio/blob/main/src/client/bv-client.cc#L146 to take in a `bv_config` https://github.com/mochi-hpc/benvolio/blob/main/src/client/bv-client.cc#L48 instead of an ssg group file, and a helper utility to turn that group file into the required `bv_config_t` struct  https://github.com/mochi-hpc/benvolio/blob/main/src/client/bv-client.cc#L647

Why all that work?  in ROMIO I can have one process load the ssg group file instead of N (where N could be quite large) and use MPI_BCAST to share with everyone.  https://github.com/roblatham00/mpich/blob/benvolio/src/mpi/romio/adio/ad_benvolio/ad_bv_common.c#L49

What would be the "bedrock way" of sharing information with all clients in a similarly scalable fashion?   A perfectly acceptable answer is "file systems handle simultaneous reads of small files just fine".

**Comment by mdorier** [comment]
I'm not sure I understand the problem. The first link (SSGManager) points to code that executes on Bedrock servers, not clients (unless your clients also act as Bedrock servers). If Bedrock servers are deployed all at the same time via MPI, the method to use is "mpi", not "join". The "join" method is there explicitly to have a new process join an existing group, with an existing SSG file present (and from experience if many processes try to join at the same time, SSG will have issues because SWIM won't manage to propagate the information fast enough).

If you want a client to interact with a Bedrock process, you need to create a ServiceHandle object, which takes a string address. How you obtained such an address is on you. For example bedrock-query reads the addresses from an SSG file here: https://github.com/mochi-hpc/mochi-bedrock/blob/main/bin/bedrock-query.cpp#L131
In an MPI application, you could imagine such a function being called only by one rank, and the information being propagated to other clients via MPI.

**Comment by roblatham00** [comment]
Sounds like you've adequately explained the solution to me.  I retract this issue!
